base.url=https://www.globalsqa.com/angularJs-protractor/BankingProject/#/login
environment=demo
browser=chromium
headless=false
timeout.ms=15000
action.timeout.ms=30000
screenshot.on.failure=true
trace.on.failure=true
record.video=false
record.har=false
artifacts.dir=test-results
report.auto.open=true
api.base.url=https://jsonplaceholder.typicode.com
